services:
  lsems-paperwork-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: lsems-paperwork-dev
    ports:
      - "${PORT:-5173}:5173"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  lsems-paperwork-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        VITE_APP_NAME: ${VITE_APP_NAME}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: lsems-divisional-paperwork-prod
    ports:
      - "8080:80"
      - "8443:8443"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
