import {useStorage} from '@vueuse/core'

export default () => ({
    darkMode: useStorage('darkMode', true),
    loading: false,
    links: {
        dutyReport: 'https://gov.eclipse-rp.net/viewforum.php?f=755',
        email: 'https://gov.eclipse-rp.net/ucp.php?i=pm&folder=inbox',
        patientFile: 'https://gov.eclipse-rp.net/viewforum.php?f=1223',
        publicRequest: 'https://gov.eclipse-rp.net/viewforum.php?f=3641',
        prescription: 'https://gov.eclipse-rp.net/viewforum.php?f=2710',
        saaaCert: 'https://gov.eclipse-rp.net/viewforum.php?f=3462',
    },
    siteLogo: 'https://i.imgur.com/9uGiPqF.png',
    divisionalLogos: {
        amu: 'https://i.imgur.com/QYXPM0p.png',
        ar: '',
        bls: '',
        cru: '',
        forensics: '',
        fr: '',
        ftd: '',
        mr: '',
        pr: '',
        red: '',
    },
    userData: useStorage('userdata', {
        name: 'FirstName LastName',
        divisionalRanks: {
            amu: '',
            ar: '',
            bls: '',
            cru: '',
            forensics: '',
            fr: '',
            ftd: '',
            mr: '',
            pr: '',
            red: '',
        },
        rank: 'Rank',
        signature: '',
        monday: '',
        tuesday: '',
        wednesday: '',
        thursday: '',
        friday: '',
        saturday: '',
        sunday: '',
        phone: '',
    }),
})
